config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: 'auth', path_names:
      {
          sign_in: 'login',
          sign_out: 'logout',
          password: 'secret',
          confirmation: 'verification',
          unlock: 'unblock',
          registration: 'register',
          sign_up: 'cmon_let_me_in'
      }
  root to: "tasks#index"

  put 'application/locale/:locale', to: 'application#locale', as: "set_locale"

  get '/', to:'tasks#index'
  # resources :tasks do
  #   get 'create', to: 'tasks#new'
  #   post 'create', to: 'tasks#create'
  # end
  get 'tasks/new', to: 'tasks#new', as:'new_task'
  get 'tasks/edit', to: 'tasks#edit', as:'edit_task'
  post 'tasks/new', to: 'tasks#create', as:'create_task'
  patch 'tasks/update/:id', to: 'tasks#update', as: 'update_task'
  delete 'tasks/delete/:id', to: 'tasks#delete', as: 'delete_task'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
  validates :name, presence: { message: "name is required" }
  validates :name, length: { minimum: 3 }

  validates :importance, inclusion: { in: %w(high middle low),
                                      message: "%{value} is not a valid size" }

  enum :importance => [:high, :middle, :low]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :tasks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_locale, :authenticate_user!


  protect_from_forgery prepend: true

  def set_locale
    I18n.locale = params[:locale] || session[:locale] || I18n.default_locale
    if user_signed_in?
      I18n.locale = current_user.locale
    end
    session[:locale] = I18n.locale
  end

  def default_url_options(options = {})
    { locale: I18n.locale }.merge options
  end

  def locale
    I18n.locale = params[:locale] || I18n.default_locale
    if current_user
      current_user.update!(locale: params[:locale])
    end
    redirect_to(request.env["HTTP_REFERER"])
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def index
    @tasks = current_user.tasks.order("expiry").all
    respond_to do |format|
      format.html{render 'tasks/index'}
      format.json{render json:  @tasks, status: :ok }
    end
  end

  # def new
  #   respond_to do |format|
  #     format.html{render 'tasks/new'}
  #     format.json{render json:  @task, status: 	:unprocessable_entity}
  #   end
  # end

  def create
    @task = current_user.tasks.create(task_create_params)
    if @task.valid?
      respond_to do |format|
        format.html{render '/'}
        format.json{render json:  @task, status: 	:ok }
      end    else
      if @task.errors.any?
        flash[:alert] = []
        @task.errors.full_messages.each do |msg|
          flash[:alert] << msg
        end
      end
      # @task = task
      respond_to do |format|
        format.html{render 'tasks/new'}
        format.json{render json:  @task, status: 	:unprocessable_entity }
      end

    end
  end

  def edit
    @task = current_user.tasks.find_by(id: params[:id])
    unless @task
      redirect_to '/'
    end
  end

  def update
    task = current_user.tasks.find_by(id: params[:id])
    if task && params[:task]
      task.update!(task_update_params)
    end
    redirect_to '/'
  end

  def delete
    task = current_user.tasks.find_by(id: params[:id])
    if task
      task.destroy!
    end
    redirect_to '/'
  end

  def task_create_params
    params.require(:task).permit(:name, :description, :importance, :expiry)
  end

  def task_update_params
    params.require(:task).permit(:name, :description, :importance, :expiry, :done)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SimpleCrud</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="container">
    <div class="header clearfix">
      <nav>
        <ul class="nav nav-pills float-right">
          <li>
              <%= link_to "EN", set_locale_path(locale: "en"), method: :put %> |
              <%= link_to "RU", set_locale_path(locale: "ru"), method: :put %>
          </li>
        </ul>
      </nav>
      <h2 class="text-muted">Task list</h2>
    </div>


    <p class="notice"><%= notice %></p>
    <p class="alert text-danger"><%= alert %></p>

    <div>
      <%= yield %>
    </div>
    <p><%= link_to t('sign_out'), destroy_user_session_path, method: :delete %></p>

    <footer class="footer">
      <p>&copy; World ORT 2017</p>
    </footer>

  </div>
  </body>
</html>

app/views/tasks/edit.html.erb
<%= form_for @task, url: update_task_path(@task.id.to_s) do |f| -%>
    <div> <%= f.hidden_field :id, value: @task.id %>
    <div>  <%= f.text_field :name, value: @task.name %></div>
    <div>  <%= f.text_field :description, value: @task.description %></div>
    <div>  <%= f.text_field :importance, placeholder: t('importance') %></div>
    <div>  <%= f.date_select :expiry, order: [:day, :month, :year] %></div>
    <div>   <%= f.check_box :done %></div>
    <div>   <%= f.submit t('save') %></div>
<% end %>

app/views/tasks/index.html.erb
<div>

  <%= link_to t('new_task'), 'tasks/new', class: 'btn btn-secondary'%>

  <% @tasks.each do |task| %>
    <% if task.done %>
      <% card_color = 'bg-success' %>
    <% else %>
      <% card_color = case task.importance %>
        <% when "high"%>
          <% 'bg-danger'%>
        <%when "middle"%>
          <%'bg-warning'%>
        <%  when "low"%>
          <%'bg-light'%>
      <% end %>
    <% end %>
  <div class="card <%= card_color %>">
    <div class="card-body">
      <h4 class="card-title"><%= task.name %></h4>
      <p class="card-text"><%= task.description %></p>
        <span class="badge badge-light">
          <a href="#" class="card-link"><%= link_to t('edit'), edit_task_path(id: task.id)%></a>
        </span>
        <span class="badge badge-light">
          <a href="#" class="card-link"><%= link_to t('delete'), delete_task_path(id: task.id), method: :delete %></a>
        </span>
        <span class="float-right"><%= task.expiry %></span>
    </div>
  </div>
  <% end %>

</div>

app/views/tasks/new.html.erb
<%= form_for :task do |f|-%>
  <div><%= f.text_field :name, placeholder: t('name') %></div>
  <div><%= f.text_field :description, placeholder: t('description') %></div>
  <div><%= f.text_field :importance, placeholder: t('importance') %></div>
  <div><%= f.date_select :expiry, order: [:day, :month, :year] %></div>
  <div><%= f.submit t("save") %></div>
<% end %>